# TOMCAT 1                # ports:
                #         - "8082:8080"
                #         - "8009:8009"
FROM tomcat:9.0

# need the server.xml here
COPY server.xml /usr/locl/tomcat/conf

# deploy war here?

# expose ajp13 port
EXPOSE 8009