version: "3"
services:
        httpd:
                container_name: httpd
                restart: always
                build: ./httpd
                networks:
                        static-network:
                                ipv4_address: "192.168.10.10"
        # To add a new tomcat node, just copy and add a new service definition, then change the
        # container_name and ipv4_address
        tomcat1:
                container_name: tomcat1
                build: ./tomcat
                depends_on:
                        - httpd
                networks:
                        static-network:
                                ipv4_address: "192.168.10.21"
        tomcat2:
                container_name: tomcat2
                build: ./tomcat
                depends_on:
                        - httpd
                networks:
                        static-network:
                                ipv4_address: "192.168.10.22"

networks:
        static-network:
                driver: bridge
                ipam:
                        driver: default
                        config:
                                - subnet: 192.168.10.0/24
