version: "3"
services:
        httpd:
                container_name: httpd
                restart: always
                build: ./httpd
                networks:
                        static-network:
                                ipv4_address: "192.168.10.10"
        tomcat1:
                container_name: tomcat1
                build: ./tomcat1
                depends_on:
                        - httpd
                networks:
                        static-network:
                                ipv4_address: "192.168.10.21"
        tomcat2:
                container_name: tomcat2
                build: ./tomcat2
                depends_on:
                        - httpd
                networks:
                        static-network:
                                ipv4_address: "192.168.10.22"

networks:
        static-network:
                driver: bridge
                ipam:
                        driver: default
                        config:
                                - subnet: 192.168.10.0/24
