version: "3"
services:
        nginx:
                container_name: nginx
                build: ./nginx
                restart: always
                networks:
                        static-network:
                                ipv4_address: "192.168.10.10"
        tomcat1:
                container_name: tomcat1
                build: ./tomcat
                depends_on:
                        - nginx
                networks:
                        static-network:
                                ipv4_address: "192.168.10.21"
        tomcat2:
                container_name: tomcat2
                build: ./tomcat
                depends_on:
                        - nginx
                networks:
                        static-network:
                                ipv4_address: "192.168.10.22"

networks:
        static-network:
                driver: bridge
                ipam:
                        driver: default
                        config:
                                - subnet: 192.168.10.0/24
