version: '3'
services:
        httpd:

        tomcat1:

        tomcat2:

        rabbitmq1:

        rabbitmq2:

networks:
        static-network:
                ipam:
                        config:
                                - subnet: 192.168.10.0/16
